defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

project_name: "ChessZero"

hydra:
  run:
    dir: .
  output_subdir: null
  hydra_logging:
    level: ERROR

model:
  depth: 7
  filter_count: 128

mcts:
  simulations: 2

buffer:
  size: 10000
  min_size: 2000

train:
  num_epochs: 15
  batch_size: 2
  seed: 42
  worker_count: 10
  learning_rate: 0.001
  self_play_steps: 200
  iterations: 2
  max_eval_pool: 10
  load_checkpoint: False

interface:
  start_player: white