defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

project_name: "HnefataflZero"

hydra:
  run:
    dir: .
  output_subdir: null
  hydra_logging:
    level: ERROR

model:
  depth: 7
  filter_count: 256

mcts:
  simulations: 2

train:
  iterations: 10
  batch_size: 2
  self_play_steps: 100
  num_epochs: 15
  max_eval_pool: 10
  seed: 42
  tqdm_interval: 5.0
  learning_rate: 0.001
  load_checkpoint: False
  eval_interval: 5
  eval_start: 25

interface:
  start_player: white